Update v0.4.4: python (e.g. qutebrowser) compatibility

diff --git a/xcolor b/xcolor
--- a/xcolor
+++ b/xcolor
@@ -2,7 +2,7 @@
 
 set -eCu
 
-VERSION="0.4.3"
+VERSION="0.4.4"
 
 OPTS=":hvlcrfs:d:t:"
 
@@ -80,6 +80,9 @@ check_cache_dir() {
     fi
     if   [ -f "$CACHE_DIR"/xcolor.rasi ]; then
         rm -f "$CACHE_DIR"/xcolor.rasi
+    fi
+    if   [ -f "$CACHE_DIR"/xcolor.py ]; then
+        rm -f "$CACHE_DIR"/xcolor.py
     fi
 }
 
@@ -284,6 +287,35 @@ read_theme() {
     done < "$THEME_PATH"
 }
 
+copy_theme() {
+    rm -f "$CONFIG_DIR"/x.colors
+    printf "! Current xcolor theme: %s\n\n" "$THEME" > "$CONFIG_DIR/x.colors"
+    cat "$THEME_PATH" >> "$CONFIG_DIR"/x.colors
+}
+
+check_xres() {
+    # Create .Xresources if not already there
+    if ! [ -f "$XRES_PATH" ]; then
+        touch "$XRES_PATH"
+    fi
+
+    # Add x.colors include path to xres if not already there
+    ! grep "$XRES_INCL" "$XRES_PATH" > /dev/null
+    if [ "$?" -ne "1" ]; then
+        # TODO: Check return value of tmp file creation
+        echo "$XRES_INCL" | cat - "$XRES_PATH" > /tmp/xcolor.xres
+        mv /tmp/xcolor.xres "$XRES_PATH"
+    fi
+
+    # Add xcolor defines to xres if not already there
+    ! grep "\*\.color[0-9]\+:\s\+COLOR[0-9]\+" "$XRES_PATH" > /dev/null
+    if [ "$?" -ne "1" ]; then
+        echo "$XRES_DEFS" >> "$XRES_PATH"
+    fi
+}
+
+## Cache Functions ##
+
 make_esc_seq() {
     echo "\
 ]4;0;$COLOR0\\\
@@ -335,31 +367,37 @@ make_rasi() {
 }" > "$CACHE_DIR"/xcolor.rasi
 }
 
-check_xres() {
-    # Create .Xresources if not already there
-    if ! [ -f "$XRES_PATH" ]; then
-        touch "$XRES_PATH"
-    fi
+make_py() {
+    echo "\
+#!/usr/bin/env python3
 
-    # Add x.colors include path to xres if not already there
-    ! grep "$XRES_INCL" "$XRES_PATH" > /dev/null
-    if [ "$?" -ne "1" ]; then
-        # TODO: Check return value of tmp file creation
-        echo "$XRES_INCL" | cat - "$XRES_PATH" > /tmp/xcolor.xres
-        mv /tmp/xcolor.xres "$XRES_PATH"
-    fi
-
-    # Add xcolor defines to xres if not already there
-    ! grep "\*\.color[0-9]\+:\s\+COLOR[0-9]\+" "$XRES_PATH" > /dev/null
-    if [ "$?" -ne "1" ]; then
-        echo "$XRES_DEFS" >> "$XRES_PATH"
-    fi
+xcdict = {
+    'foreground':    '$FOREGROUND',
+    'background':    '$BACKGROUND',
+    'cursor':        '$CURSOR',
+    'color0':        '$COLOR0', # Black   (Normal)
+    'color1':        '$COLOR1', # Red     (Normal)
+    'color2':        '$COLOR2', # Yellow  (Normal)
+    'color3':        '$COLOR3', # Green   (Normal)
+    'color4':        '$COLOR4', # Blue    (Normal)
+    'color5':        '$COLOR5', # Magenta (Normal)
+    'color6':        '$COLOR6', # Cyan    (Normal)
+    'color7':        '$COLOR7', # White   (Normal)
+    'color8':        '$COLOR8', # Black   (Bright)
+    'color9':        '$COLOR9', # Red     (Bright)
+    'color10':       '$COLOR10', # Yellow  (Bright)
+    'color11':       '$COLOR11', # Green   (Bright)
+    'color12':       '$COLOR12', # Blue    (Bright)
+    'color13':       '$COLOR13', # Magenta (Bright)
+    'color14':       '$COLOR14', # Cyan    (Bright)
+    'color15':       '$COLOR15', # White   (Bright)
+}" > "$CACHE_DIR"/xcolor.py
 }
 
-copy_theme() {
-    rm -f "$CONFIG_DIR"/x.colors
-    printf "! Current xcolor theme: %s\n\n" "$THEME" > "$CONFIG_DIR/x.colors"
-    cat "$THEME_PATH" >> "$CONFIG_DIR"/x.colors
+make_cache_files() {
+    make_esc_seq
+    make_rasi
+    make_py
 }
 
 ## Reload Functions ##
@@ -423,8 +461,7 @@ done
 # Update current TTYs
 read_theme
 check_cache_dir
-make_esc_seq
-make_rasi
+make_cache_files
 rel_tty
 
 exit 0
